const URL="https://fcegavhipeaeihxegsnw.supabase.co";
const KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXAiLCJyZWYiOiJmY2VnYXZoaXBlYWVpaHhlZ3NudyIsInJvbGUiOiJhbm9uIiwiaWF0IjoxNzYyMTI5NzU3LCJleHAiOjIwNzc3MDU3NTd9.i-ZjOlKc89-uA7fqOIvmAMv60-C2_NmKikRI_78Jei8";
const sb=window.supabase.createClient(URL,KEY,{auth:{persistSession:true,flowType:"pkce",autoRefreshToken:true}});
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
let certs=[];
function clock(){if($("#clock"))$("#clock").textContent=new Date().toLocaleTimeString("en-SG",{hour:"2-digit",minute:"2-digit",hour12:false})}clock();setInterval(clock,30000);
async function boot(){
 const {data:{session}}=await sb.auth.getSession();if(!session){location.replace("auth.html");return}
 const uid=session.user.id;
 const [prof,certReq,earnedReq,reqReq,assignReq]=await Promise.all([sb.from("profiles").select("*").eq("user_id",uid).maybeSingle(),sb.from("certifications").select("*"),sb.from("user_certifications").select("certification_code,awarded_at").eq("user_id",uid),sb.from("certification_requirements").select("*"),sb.from("academy_specialisation_assignments").select("*").eq("user_id",uid).maybeSingle()]);
 certs=certReq.data||[];const p=prof.data||{},earned=earnedReq.data||[],reqs=reqReq.data||[],assignment=assignReq.data||null,set=new Set(earned.map(x=>(x.certification_code||"").toUpperCase()));
 const name=p.display_name||p.handle||session.user.email?.split("@")[0]||"CREW";$("#userName").textContent=name.toUpperCase();$(".avatar").textContent=name[0]?.toUpperCase()||"J";$("#net").textContent="SECURE";$("#syncText").textContent="Live sync · "+new Date().toLocaleTimeString("en-SG",{hour:"2-digit",minute:"2-digit"});
 $("#academyTotal").textContent=certs.length;$("#academyEarned").textContent=earned.length;$("#academyCurrent").textContent=(assignment?.specialisation_code||(!set.has("BMT")?"BMT":!set.has("SOC")?"SOC":"SUPPORT")).toUpperCase();
 const node=(code,label,done,locked=false)=>'<div class="academy-path-node '+(done?"done ":"")+(locked?"locked":"")+'"><span>'+esc(code)+'</span><b>'+esc(label)+'</b><small>'+(done?"CERTIFIED":locked?"LOCKED":"AVAILABLE")+'</small></div>';
 const bmt=set.has("BMT"),soc=set.has("SOC");$("#academyPathTrack").innerHTML=node("BMT","Basic Military Training",bmt)+'<i>→</i>'+node("SOC","Standard Obstacle Course",soc,!bmt)+'<i>→</i><div class="academy-path-branches"><div><small>SUPPORT PATHWAYS</small>'+["MED","LOG","MIN","PILOT"].map(x=>node(x,x,set.has(x),!soc)).join("")+'</div><div><small>ACTIVE SPECIALISATION</small>'+node(assignment?.specialisation_code||"—",assignment?.specialisation_code||"Awaiting assignment",set.has((assignment?.specialisation_code||"").toUpperCase()),!assignment).replace("academy-path-node","academy-path-node special")+'</div></div>';
 render("all",set,reqs,assignment);$$("[data-acfilter]").forEach(b=>b.onclick=()=>{$$("[data-acfilter]").forEach(x=>x.classList.toggle("active",x===b));render(b.dataset.acfilter,set,reqs,assignment)});
}
function render(filter,set,reqs,assignment){const kind=c=>["BMT","SOC"].includes(c)?"core":["GUNNERY","ENGINEERING"].includes(c)?"specialisation":"support";const items=certs.filter(x=>filter==="all"||kind((x.certification_code||"").toUpperCase())===filter);$("#certGrid").innerHTML=items.map(c=>{const code=(c.certification_code||"").toUpperCase(),done=set.has(code),total=reqs.filter(r=>(r.certification_code||"").toUpperCase()===code).length,k=kind(code),art=c.big_art_cover||c.image_url||"https://fcegavhipeaeihxegsnw.supabase.co/storage/v1/object/public/frontpage/Academy.png";let status=done?"CERTIFIED":code==="SOC"&&!set.has("BMT")?"LOCKED":k==="specialisation"&&assignment?.specialisation_code!==code?"ASSIGNMENT REQUIRED":"AVAILABLE";return '<article class="academy-programme '+status.toLowerCase().replaceAll(" ","-")+'"><div class="academy-programme-art"><img src="'+esc(art)+'"><span>'+esc(code)+'</span></div><div class="academy-programme-body"><small>'+k.toUpperCase()+' PATHWAY</small><h3>'+esc(c.name||code)+'</h3><p>'+esc(c.description||"JMBN Academy certification programme.")+'</p><div class="academy-programme-foot"><b>'+status+'</b><span>'+total+' TRAINING REQUIREMENTS</span></div></div></article>'}).join("")}
boot();