let origin=null,minutes=60,mode="all",filter="all";
let saved=new Set(JSON.parse(localStorage.getItem("otg.saved")||"[]"));
let places=[];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const toast=m=>{const t=$("#toast");t.textContent=m;t.classList.add("show");clearTimeout(window._t);window._t=setTimeout(()=>t.classList.remove("show"),2200)};
const esc=s=>String(s||"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
function dist(a,b,c,d){const R=6371,p=x=>x*Math.PI/180,dp=p(c-a),dl=p(d-b),h=Math.sin(dp/2)**2+Math.cos(p(a))*Math.cos(p(c))*Math.sin(dl/2)**2;return R*2*Math.atan2(Math.sqrt(h),Math.sqrt(1-h))}
function score(x){let s=0;s+=Math.max(0,35-x.km*9);if(x.wikipedia)s+=24;if(x.wikidata)s+=18;if(/attraction|museum|viewpoint|gallery|artwork|castle|monument|temple|shrine|garden/i.test(x.type))s+=10;if(x.km<.8)s+=10;if(minutes<=90&&x.km<1)s+=8;return s}
function render(){let rows=[...places].sort((a,b)=>score(b)-score(a));if(filter==="saved")rows=rows.filter(x=>saved.has(x.id));if(filter==="quick")rows=rows.filter(x=>x.km<.8);$("#empty").classList.toggle("hidden",rows.length>0);$("#results").innerHTML=rows.slice(0,8).map((x,i)=>`<article class="result ${i===0?"featured":""}"><div class="result-top"><span class="type">${esc(x.type)}</span><button class="save ${saved.has(x.id)?"on":""}" data-save="${esc(x.id)}">${saved.has(x.id)?"♥":"♡"}</button></div><h3>${esc(x.name)}</h3><p>${x.wikipedia?"Notable nearby place with Wikipedia/Wikidata context.":"Nearby discovery that fits your current area."}</p><div class="result-bottom"><span>◎ ${x.km.toFixed(1)} km</span><span class="badge">${x.km<.8?"Quick stop":"Nearby"}</span><button class="go" data-go="${esc(x.id)}">Go ↗</button></div></article>`).join("");
$$("[data-save]").forEach(b=>b.onclick=()=>{saved.has(b.dataset.save)?saved.delete(b.dataset.save):saved.add(b.dataset.save);localStorage.setItem("otg.saved",JSON.stringify([...saved]));render()});
$$("[data-go]").forEach(b=>b.onclick=()=>{const x=places.find(p=>p.id===b.dataset.go);if(x)window.open(`https://www.google.com/maps/dir/?api=1&destination=${x.lat},${x.lon}`,"_blank")})}
async function discover(lat,lon,label="Near you"){origin={lat,lon};$("#locText").textContent=label;$("#resultTitle").textContent="What’s worth considering";$("#resultKicker").textContent=minutes+" MINUTES FREE";$("#resultsSection").scrollIntoView({behavior:"smooth"});$("#empty").innerHTML="<span>⌁</span><b>Looking around…</b><p>Finding sights, culture, nature and notable places.</p>";
const q=`[out:json][timeout:18];(nwr["tourism"~"attraction|museum|gallery|viewpoint|artwork"](around:2500,${lat},${lon});nwr["historic"](around:2500,${lat},${lon});nwr["leisure"~"park|garden|nature_reserve"](around:2500,${lat},${lon});nwr["amenity"="place_of_worship"]["name"](around:2500,${lat},${lon}););out center tags;`;
try{const r=await fetch("https://overpass-api.de/api/interpreter",{method:"POST",body:q});const d=await r.json();const seen=new Set();places=d.elements.map(e=>{const t=e.tags||{},c=e.center||e,n=t["name:en"]||t.name;if(!n||!c.lat||!c.lon)return null;const key=n.toLowerCase();if(seen.has(key))return null;seen.add(key);return{id:"osm-"+e.type+"-"+e.id,name:n,type:t.tourism||t.historic||t.leisure||t.amenity||"place",lat:c.lat,lon:c.lon,km:dist(lat,lon,c.lat,c.lon),wikidata:t.wikidata,wikipedia:t.wikipedia}}).filter(Boolean);render();if(!places.length)toast("No strong nearby matches found.")}catch(e){places=[];render();toast("Nearby search is busy. Try refresh.")}}
function useLocation(){if(!navigator.geolocation)return toast("Location is unavailable.");$("#locText").textContent="Finding you…";navigator.geolocation.getCurrentPosition(p=>discover(p.coords.latitude,p.coords.longitude,"Current location"),()=>{toast("Location permission wasn’t granted.");$("#locText").textContent="Use my location"},{enableHighAccuracy:true,timeout:10000,maximumAge:60000})}
async function geocode(name){try{const r=await fetch("https://nominatim.openstreetmap.org/search?format=json&limit=1&q="+encodeURIComponent(name),{headers:{"Accept":"application/json"}});const d=await r.json();if(!d[0])return toast("I couldn’t find that place.");closeSheets();discover(+d[0].lat,+d[0].lon,name)}catch(e){toast("Place search failed. Try again.")}}
function openSheet(id){$("#"+id).classList.remove("hidden")}function closeSheets(){$$(".sheet").forEach(x=>x.classList.add("hidden"))}
$$(".close").forEach(b=>b.onclick=closeSheets);$$(".sheet").forEach(s=>s.onclick=e=>{if(e.target===s)closeSheets()});
$$(".time").forEach(b=>b.onclick=()=>{minutes=+b.dataset.min;$$(".time").forEach(x=>x.classList.toggle("active",x===b));if(origin)discover(origin.lat,origin.lon,$("#locText").textContent)});
$$(".chip").forEach(b=>b.onclick=()=>{filter=b.dataset.filter;$$(".chip").forEach(x=>x.classList.toggle("active",x===b));render()});
$("#locBtn").onclick=useLocation;$("#aroundMe").onclick=useLocation;$("#whatNow").onclick=()=>origin?discover(origin.lat,origin.lon,$("#locText").textContent):useLocation();
$("#aroundPlace").onclick=()=>openSheet("placeSheet");$("#placeForm").onsubmit=e=>{e.preventDefault();geocode($("#placeInput").value.trim())};
$("#refreshBtn").onclick=()=>origin&&discover(origin.lat,origin.lon,$("#locText").textContent);
$("#anchorBtn").onclick=()=>openSheet("anchorSheet");$("#saveAnchor").onclick=()=>{const n=$("#anchorName").value.trim(),t=$("#anchorTime").value;if(!n)return toast("Add the booking or must-do first.");localStorage.setItem("otg.anchor",JSON.stringify({n,t}));loadAnchor();closeSheets();toast("Anchor saved")};
function loadAnchor(){const a=JSON.parse(localStorage.getItem("otg.anchor")||"null");if(!a)return;$("#anchorTitle").textContent=(a.t?a.t+" · ":"")+a.n;$("#anchorSub").textContent="We’ll keep flexible suggestions around this.";$("#timelineAnchor").textContent=a.n+(a.t?" · "+a.t:"")}
$("#expense").onclick=()=>openSheet("expenseSheet");$("#receiptInput").onchange=e=>{const f=e.target.files[0];if(!f)return;$("#receiptPreview").src=URL.createObjectURL(f);$("#receiptPreview").classList.remove("hidden");$("#receiptConfirm").classList.remove("hidden");toast("Receipt ready — OCR connection is the next backend step.")};
$("#saveExpense").onclick=()=>{const amount=$("#amount").value.trim();if(!amount)return toast("Confirm the amount first.");const rows=JSON.parse(localStorage.getItem("otg.expenses")||"[]");rows.push({amount,category:$("#category").value,date:new Date().toISOString()});localStorage.setItem("otg.expenses",JSON.stringify(rows));closeSheets();toast("Expense saved")};
$("#food").onclick=()=>toast("Food Finder will use your Google Places candidate-pool logic.");
$("#navPlan").onclick=()=>$(".today").scrollIntoView({behavior:"smooth"});$("#navSaved").onclick=()=>{filter="saved";$$(".chip").forEach(x=>x.classList.toggle("active",x.dataset.filter==="saved"));$("#resultsSection").scrollIntoView({behavior:"smooth"});render()};$("#navMore").onclick=()=>toast("More trip tools can live here without cluttering What Now.");
loadAnchor();render();