const demoPlaces=[
 {id:"arashiyama",name:"Arashiyama Bamboo Grove",type:"nature",desc:"A calm green walk when you want to reset your head.",distance:"8 min",tag:"Quiet start",quick:true,featured:true},
 {id:"nijo",name:"Nijō Castle",type:"culture",desc:"Wooden corridors, gardens and a little history without a full-day commitment.",distance:"14 min",tag:"Worth it"},
 {id:"kamo",name:"Kamo River",type:"nature",desc:"Grab a drink and walk until the city feels lighter.",distance:"11 min",tag:"Easy escape",quick:true},
 {id:"gion",name:"Gion backstreets",type:"neighbourhood",desc:"Lantern-lit lanes, small shops and a good reason to wander.",distance:"16 min",tag:"Go now"},
 {id:"tea",name:"A quiet tea house",type:"cafe",desc:"A small pause, something warm, and nowhere else to be.",distance:"6 min",tag:"Slow down",quick:true},
 {id:"nishiki",name:"Nishiki Market",type:"food & market",desc:"A lively wander when you want to taste your way through the neighbourhood.",distance:"13 min",tag:"Crowded but fun"}
];
let livePlaces=[...demoPlaces], saved=new Set(JSON.parse(localStorage.getItem("onthego.saved")||"[]")), activeMode="all", activeFilter="all", locationState=null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function toast(message){const t=$("#toast");t.textContent=message;t.classList.add("show");clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove("show"),2600)}
function save(){localStorage.setItem("onthego.saved",JSON.stringify([...saved]))}
function render(){let rows=livePlaces.filter(x=>activeMode==="all"||activeMode==="place"?(activeMode==="all"||x.type!=="food"):x.type==="food");if(activeFilter==="saved")rows=rows.filter(x=>saved.has(x.id));if(activeFilter==="quick")rows=rows.filter(x=>x.quick);$("#results").innerHTML=rows.map((x,i)=>`<article class="result-card ${x.featured?"featured":""}"><div><div class="result-top"><span class="result-type">${x.type}</span><button class="save-btn ${saved.has(x.id)?"saved":""}" data-save="${x.id}">${saved.has(x.id)?"♥":"♡"}</button></div><h3>${x.name}</h3><p>${x.desc}</p></div><div class="card-bottom"><span class="distance">⌖ ${x.distance||"Nearby"}</span><span class="tag">${x.tag||"Explore"}</span><button class="go-button" data-go="${x.id}">Go ↗</button></div></article>`).join("");$("#emptyState").classList.toggle("hidden",!rows.length);$$("[data-save]").forEach(b=>b.onclick=()=>{const id=b.dataset.save;saved.has(id)?saved.delete(id):saved.add(id);save();render();toast(saved.has(id)?"Saved for later":"Removed from saved")});$$("[data-go]").forEach(b=>b.onclick=()=>{const item=livePlaces.find(x=>x.id===b.dataset.go);if(item)window.open("https://www.openstreetmap.org/search?query="+encodeURIComponent(item.name)," _blank")})}
async function useLocation(){if(!navigator.geolocation){toast("Location is not available in this browser.");return}$("#locationLabel").textContent="Finding you…";navigator.geolocation.getCurrentPosition(async p=>{locationState={lat:p.coords.latitude,lon:p.coords.longitude};$("#locationLabel").textContent="Location active";$("#contextTitle").textContent="Near you";$("#contextSub").textContent="Live nearby results from OpenStreetMap";await loadOverpass();toast("Nearby results updated")},()=>{$("#locationLabel").textContent="Use my location";toast("Location permission was not granted")},{enableHighAccuracy:true,timeout:10000,maximumAge:60000})}
async function loadOverpass(){if(!locationState)return;const q=`[out:json][timeout:20];(nwr["tourism"](around:2200,${locationState.lat},${locationState.lon});nwr["leisure"~"park|nature_reserve|garden"](around:2200,${locationState.lat},${locationState.lon});nwr["historic"](around:2200,${locationState.lat},${locationState.lon}););out center tags;`;try{const r=await fetch("https://overpass-api.de/api/interpreter",{method:"POST",body:q});const data=await r.json();const mapped=data.elements.map((e,i)=>{const t=e.tags||{},c=e.center||e;return{id:"osm-"+e.type+"-"+e.id,name:t.name||t["name:en"]||"Nearby place",type:t.tourism||t.historic||t.leisure||"place",desc:"An OpenStreetMap discovery close to you.",distance:locationState?Math.round(distance(locationState.lat,locationState.lon,c.lat,c.lon)/80)+" min":"Nearby",tag:"OSM discovery",quick:i<4,lat:c.lat,lon:c.lon}}).filter(x=>x.name!=="Nearby place");if(mapped.length){livePlaces=[...mapped.slice(0,12),...demoPlaces.slice(0,2)];render()}}catch(e){toast("Could not load nearby places right now.")}}
function distance(a,b,c,d){const R=6371000,p=a*Math.PI/180,q=c*Math.PI/180,dp=(c-a)*Math.PI/180,dl=(d-b)*Math.PI/180,h=Math.sin(dp/2)**2+Math.cos(p)*Math.cos(q)*Math.sin(dl/2)**2;return R*2*Math.atan2(Math.sqrt(h),Math.sqrt(1-h))}
function choosePlace(){const place=prompt("Where are you now? Try: Arashiyama, Kyoto");if(!place)return;$("#contextTitle").textContent=place;$("#contextSub").textContent="Showing nearby OpenStreetMap ideas";toast("Place selected — live geocoding can be connected next")}
$("#locationBtn").onclick=useLocation;$("#changePlaceBtn").onclick=choosePlace;$("#exploreBtn").onclick=()=>{activeMode="place";$$(".mode-card").forEach(x=>x.classList.toggle("active",x.dataset.mode==="place"));render();window.scrollTo({top:470,behavior:"smooth"})};$("#themeBtn").onclick=()=>{document.body.classList.toggle("dark");toast("Theme updated")};$("#savedNav").onclick=()=>{$$(".filter-button").forEach(x=>x.classList.toggle("active",x.dataset.filter==="saved"));activeFilter="saved";render()};$("#mapNav").onclick=()=>toast(locationState?"Map view is ready for the next build":"Turn on location to open the nearby map");$("#moreNav").onclick=()=>toast("More tools are coming into OnTheGo");$$(".mode-card").forEach(b=>b.onclick=()=>{activeMode=b.dataset.mode;$$(".mode-card").forEach(x=>x.classList.toggle("active",x===b));$("#resultsHeading").textContent=activeMode==="food"?"Food around you":activeMode==="place"?"Places around you":"A little inspiration";render()});$$(".filter-button").forEach(b=>b.onclick=()=>{activeFilter=b.dataset.filter;$$(".filter-button").forEach(x=>x.classList.toggle("active",x===b));render()});render();